#!/bin/sh

### Environment Variables & Constants ###
export KEEP_ZSHRC=yes

# colors for msg output
red="\033[91m"
green="\033[92m"
blue="\033[94m"
yellow="\033[93m"
white="\033[97m"
no_color="\033[0m"

### Functions ###
print_header() {
    echo -e "${green}
       _     _   ___ _ _
     _| |___| |_|  _|_| |___ ___
   _| . | . |  _|  _| | | -_|_ -|
  |_|___|___|_| |_| |_|_|___|___|${yellow}
  BOOTSTRAP SCRIPT
" >&1
}

print_msg() {
    echo -e "${green}=>${no_color}${blue}" "${@}" "${no_color}" >&1
}

install_zsh_plugins() {
    print_msg "installing zsh plugins..."
    git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.zsh}/plugins/zsh-autosuggestions

}

### Execute Commands ###
print_header

print_msg "updating and upgrading apt-packages..."
sudo apt update && sudo apt upgrade

# install apt-packages from dotfile
print_msg "installing apt-packages from .apt-packages file..."
xargs sudo apt-get install <~/.apt-packages

# install pip-packages from dotfile
# print_msg "installing pip-packages from .pip-packages file..."
# pip install -r ~/.pip-packages

# install thefuck as pip package
print_msg "installing thefuck as a pip package..."
pip3 install thefuck --user

# install oh-my-zsh with curl
install_zsh_plugins
print_msg "installing oh-my-zsh without overwriting .zshrc..."
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
