#!/bin/sh

### Environment Variables & Constants ###
export KEEP_ZSHRC=yes

# colors for msg output
red="\033[91m"
green="\033[92m"
blue="\033[94m"
yellow="\033[93m"
white="\033[97m"
no_color="\033[0m"

### Functions ###
print_header() {
  echo "${green}
       _     _   ___ _ _
     _| |___| |_|  _|_| |___ ___
   _| . | . |  _|  _| | | -_|_ -|
  |_|___|___|_| |_| |_|_|___|___|${yellow}
  BOOTSTRAP SCRIPT
" >&1
}

print_footer() {
  echo "${yellow}
  DOTFILE BOOTSTRAP IS COMPLETE!${red}
  Log out${blue} and${red} login${blue} to apply changes!
" >&1
}

print_msg() {
  echo "${green}=>${no_color}${blue}" "${@}" "${no_color}" >&1
}

install_zsh_plugins() {
  print_msg "installing zsh plugins..."
  git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.zsh}/plugins/zsh-autosuggestions
  mkdir $ZSH_CUSTOM/plugins/poetry
  poetry completions zsh > $ZSH_CUSTOM/plugins/poetry/_poetry		
}

install_docker() {
  print_msg "installing docker..."
  sudo apt-get remove docker docker-engine docker.io containerd runc
  sudo mkdir -m 0755 -p /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  echo \
    "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" |
    sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
  sudo apt-get update
  sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
}

install_poetry() {
 print_msg "installing poetry..."
 curl -sSL https://install.python-poetry.org | python3 -
}

install_pyenv () {
  print_msg "installing pyenv..."
  sudo sudo apt install libffi-dev zlib1g zlib1g-dev libssl-dev libbz2-dev libsqlite3-dev liblzma-dev libedit-dev libreadline-dev python3-tk tk-dev
  curl https://pyenv.run | bash
}

install_lazygit () {
print_msg "installing lazygit..."
LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": "v\K[^"]*')
curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
tar xf lazygit.tar.gz lazygit
sudo install lazygit /usr/local/bin
}

### Execute Commands ###
print_header

print_msg "updating and upgrading apt-packages..."
sudo apt update && sudo apt upgrade

# install apt-packages from dotfile
print_msg "installing apt-packages from .apt-packages file..."
xargs sudo apt-get install -y <~/.apt-packages
# install pip-packages from dotfile
# print_msg "installing pip-packages from .pip-packages file..."
# pip install -r ~/.pip-packages

# install poetry
install_poetry

# install docker
install_docker

# install pyenv
install_pyenv

# install lazygit
install_lazygit

# install oh-my-zsh with curl
install_zsh_plugins
print_msg "installing oh-my-zsh without overwriting .zshrc..."
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

print_footer
