#!/bin/sh

install_oh_my_zsh() {
    # install ohmyzsh and symlink my-aliases.zsh

    sudo apt install zsh
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    sleep 5
    cd .oh-my-zsh/custom/
    ln -s ~/.zsh/my-aliases.zsh .
}

install_thefuck() {
    # install thefuck cli tool
    sudo apt update
    sudo apt install python3-dev python3-pip python3-setuptools
    pip3 install thefuck --user
}

sudo apt install curl
install_oh_my_zsh
install_thefuck
sudo apt install keychain
sudo apt install direnv




